language: python
addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev

sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/sundials

#env:
  #- TOXENV=docs
  #- TOXENV=check-manifest
  #- TOXENV=checkreadme
matrix:
  include:
    - python: 3.6
      env:
      - TOXENV=py36
    - python: 3.6
      env:
      - TOXENV=flake8
    - python: 3.6
      env:
      - TOXENV=pylint

install:
  - source ./ci_support/ensure_sundials_installed.sh
  - pip install -U pip setuptools wheel
  - pip install -c known_broken_constraints.txt --pre -U coverage # coverage major versions need to match
  - pip install -U tox codecov

script:
  - tox

after_success:
  - codecov
